version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - 8000:8000
    # command: python manage.py runserver 127.0.0.1:8000
    networks:
      - app-tier
    restart: always
    volumes:
      - ./backend/app:/app
    env_file:
      - ./backend/.env.dev

networks:
  app-tier:
    driver: bridge
